node('docker') {
  checkout scm
  env.PATH = "${tool 'Maven3'}/bin:${env.PATH}"

  stage('Package') {
    dir('demos/JavaEE/webapp') {
      sh 'mvn clean package -DskipTests'
    }
  }

  stage('Create Docker Image') {
    dir('demos/JavaEE') {
      // Start database container here
      sh 'docker-compose up --force --build -d db'
      // Build app
      sh 'docker-compose build app'
    }
  }

  stage ('Run Application') {
    try {
      dir('demos/JavaEE') {
        // Run add
        sh 'docker-compose run -e DB_URI=`docker inspect --format="{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}" db` app'
      }
      // Run tests using Maven
      //dir ('webapp') {
      //  sh 'mvn exec:java -DskipTests'
      //}
    } catch (error) {
    } finally {
      // Stop and remove database container here
      //sh 'docker-compose stop db'
      //sh 'docker-compose rm db'
    }
  }

  stage('Run Tests') {
    try {
      dir('demos/JavaEE/webapp') {
        sh "mvn test"
        // docker.build("arungupta/docker-jenkins-pipeline:${env.BUILD_NUMBER}").push()
      }
    } catch (error) {

    } finally {
      junit '**/target/surefire-reports/*.xml'
      dir('demos/JavaEE') {
        sh 'docker-compose down -v'
      }
    }
  }
}
