version: '3.3'

services:
  selenoid:
    image: aerokube/selenoid
    networks:
      default: null
    volumes:
      - "./selenoid/browsers.json:/etc/selenoid/browsers.json"
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "4444:4444"
    command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs", "-container-network", "docker_default"]

  selenoid-ui:
    image: aerokube/selenoid-ui
    networks:
      default: null
    links:
      - selenoid
    ports:
      - "8080:8080"
    command: -selenoid-uri http://selenoid:4444

  auto:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auto_project
    networks:
      default: null
    links:
      - selenoid
      - selenoid-ui
    working_dir: /auto
    volumes:
      - type: bind
        source: .
        target: /auto
    expose:
      - 4444

networks:
  default:
    external:
      name: docker_default
